const parent=document.getElementById("root");
const element=React.createElement("h1",{},"this is new heading");
const root=ReactDOM.createRoot(parent);
   // root.render(element);
const h1=React.createElement("h1",{},"shopping cart");
    //root.render([element,h1]);
const item1=React.createElement("li",{},"item-1");
const item2=React.createElement("li",{},"item-2");
const list=React.createElement("ol",{},item1,item2);
root.render([element,h1,list]);